#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_DOLYBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys

_UPSTREAM_ = "https://github.com/theend-alpha/DolyBot"
_BRANCH_ = "master"

repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_doly_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnM=" | base64 -d`
    echo "$rlink"
}

_doly_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_DOLYBOT_PLUG() {
    local hrepo=$(_doly_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local dolypath
    dolypath="Plugins.zip"
    echo "••• DOWNLOADING DOLYBOT •••"
    wget -q $(_doly_zip) -O "$dolypath"
    DOLYPATH=$(zipinfo -1 "$dolypath" | grep -v "/.");
    unzip -qq "$dolypath"
    rm -rf "$dolypath"
    # _DOLYBOT_MAIN
    cd $DOLYPATH
    # _DOLYBOT_PLUG
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING DOLYBOT •••"
    python3 -m dolybot
}

_starter
